default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('APP_DB_HOST', 'postgres') %>
  port: <%= ENV.fetch('APP_DB_PORT', '5432') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 30 } %>
  username: <%= ENV.fetch('APP_DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('APP_DB_PASSWORD', 'postgres') %>

development:
  <<: *default
  database: <%= ENV.fetch('APP_DB_NAME', 'app_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('APP_DB_NAME', 'app_test') %>
